name: V1_BuildAndDeploy_NodeApp_ToAzureWebApp

on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v1-node-sampleapp
        publish-profile: ${{ secrets.v1NodeSampleApp }}
        package: node-test/webfrontend
